<?
$aMenuLinks = Array(
	/*Array(
		"Австралия",
		"/countries/avstraliya/",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Австрия",
		"/countries/avstriya/",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Великобритания",
		"/countries/velikobritaniya/",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Гонконг",
		"/countries/gonkong/",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Греция",
		"/specialoffers/?arrFilter_pf[COUNTRY]=86&set_filter=Y",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Дания",
		"/countries/daniya/",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Израиль",
		"/specialoffers/?arrFilter_pf%5BCOUNTRY%5D=109&set_filter=Фильтр&set_filter=Y",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Испания",
		"/countries/ispaniya/",
		Array(),
		Array(),
		""
	),*/
	Array(
		"Италия",
		"/specialoffers/?arrFilter_pf%5BCOUNTRY%5D=94&set_filter=Фильтр&set_filter=Y",
		Array(),
		Array(),
		""
	),
	/*Array(
		"Кипр",
		"/countries/kipr/",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Китай",
		"/countries/kitay/",
		Array(),
		Array(),
		""
	),*/
	Array(
		"Маврикий",
		"/specialoffers/?arrFilter_pf%5BCOUNTRY%5D=153&set_filter=Фильтр&set_filter=Y",
		Array(),
		Array(),
		""
	),
	Array(
		"Мальдивы",
		"/specialoffers/?arrFilter_pf%5BCOUNTRY%5D=112&set_filter=Фильтр&set_filter=Y",
		Array(),
		Array(),
		""
	),
	/*Array(
		"Мексика",
		"/countries/meksika/",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Нидерланды",
		"/countries/niderlandy/",
		Array(),
		Array(),
		""
	),*/
	Array(
		"ОАЭ",
		"/specialoffers/?arrFilter_pf%5BCOUNTRY%5D=235&set_filter=Фильтр&set_filter=Y",
		Array(),
		Array(),
		""
	),
	/*Array(
		"Португалия",
		"/countries/portugaliya/",
		Array(),
		Array(),
		""
	),*/
	Array(
		"Сейшелы",
		"/specialoffers/?arrFilter_pf%5BCOUNTRY%5D=185&set_filter=Фильтр&set_filter=Y",
		Array(),
		Array(),
		""
	),
	/*Array(
		"Сингапур",
		"/countries/singapur/",
		Array(),
		Array(),
		""
	),*/
	Array(
		"Турция",
		"/specialoffers/?arrFilter_pf%5BCOUNTRY%5D=96&set_filter=Фильтр&set_filter=Y",
		Array(),
		Array(),
		""
	),
	/*Array(
		"Тайланд",
		"/countries/tayland/",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Франция",
		"/countries/frantsiya/",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Швейцария",
		"/countries/shveytsariya/",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"ЮАР",
		"/countries/yuar/",
		Array(),
		Array(),
		""
	),*/
);