<?
$aMenuLinks = Array(
	/*Array(
		"Австралия",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=135&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Австрия",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=97&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Великобритания",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=99&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Гонконг",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=110&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Греция",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=86&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Дания",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=117&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Израиль",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=109&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Испания",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=95&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	Array(
		"Италия",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=94&arrFilter_pf%5BRESORT%5D=&arrFilter_pf%5BCITY%5D=&set_filter=Y&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),
	/*Array(
		"Китай",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=126&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	Array(
		"Маврикий",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=153&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),
	Array(
		"Мальдивы",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=112&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),
	/*Array(
		"Мексика",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=93&arrFilter_pf%5BRESORT%5D=&arrFilter_pf%5BCITY%5D=&set_filter=Y&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Нидерланды",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=120&arrFilter_pf%5BRESORT%5D=&arrFilter_pf%5BCITY%5D=&set_filter=Y&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	Array(
		"ОАЭ",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=235&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),
	/*Array(
		"Португалия",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=84&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	Array(
		"Сейшелы",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=185&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),
	/*Array(
		"Сингапур",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=344&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	Array(
		"США",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=80&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),
	/*Array(
		"Тайланд",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=90&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Франция",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=87&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"Швейцария",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=92&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
	/*Array(
		"ЮАР",
		"/hotels/?arrFilter_pf%5BCOUNTRY%5D=123&arrFilter_pf%5BCITY%5D=&set_filter=Фильтр",
		Array(),
		Array(),
		""
	),*/
);